### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Peterosh** [mahendrakalkura/www.bet365.com#5]
Hello, I used golang to write a program according to the request process of bet365 website to obtain data.One of the websocket connections that got the data only replied to me once, then ignored me and kept opening me.Could you please tell me how you connected him and obtained the data

**Comment by mahendrakalkura** [comment]
Are you sending your topics?

**Reference:** https://github.com/mahendrakalkura/www.bet365.com/blob/master/manage.py#L91

**Comment by Peterosh** [comment]
I sending topics of "\x16\x00CONFIG_10_0,OVInPlay_10_0,Media_L10_Z0,XL_L10_Z0_C1_W3\x01"

**Comment by mahendrakalkura** [comment]
Do you see similar topics within your browser as well?

**Comment by Peterosh** [comment]
yus

**Comment by Peterosh** [comment]
yes

**Comment by Peterosh** [comment]
log：
connecting to wss://premws-pt3.365pushodds.com/zap?uid56190593074585604
connected! 
connecting to wss://pshudws.365pushodds.com/zap?uid=12176670311137530
connected! 
2recv: 100IRUD10-3/Y1bMOL+Mhn
2confirm
2write: commandgetMessage06C40583C60ED36587430C92207A2478000003SPTBK10
1recv: 100I1PIP26-A7S4Zz1Bmxcq
write: __host,CONFIG_10_0,OVInPlay_10_0,Media_L10_Z0,XL_L10_Z0_C1_W3
1confirm
2recv: EMPTYF|IN;EM=1;TO= S_06C40583C60ED36587430C92207A2478000003;|__timeF|IN;TI=20180922105115782;UF=55;|
2recv: -11111_SPTBK_10_MSGF
2recv: __timeU|IN;TI=20180922105149283;UF=55;|
2recv: __timeU|IN;TI=20180922105244282;UF=55;|
2recv: __timeU|IN;TI=20180922105339282;UF=55;|

**Comment by Peterosh** [comment]
wss://premws-pt3.365pushodds.com/zap?uid56190593074585604

**Comment by Peterosh** [comment]
wss://premws-pt3.365pushodds.com/zap?uid56190593074585604
I send  #P__time, S_2A9366FE1546FE81BB876DB7B9AC10FA000003
just recv 100�I1PIP26-A7S4Zz1Bmxcq
I send msg of �CONFIG_10_0,OVInPlay_10_0,Media_L10_Z0,XL_L10_Z0_C1_W3�
I did not receive any messages next, and he did not actively disconnect me.



If there is any problem with my operation process, please give me some advice. If you don't find any problem, it's ok. Thank you very much for taking the time to reply to my question

**Comment by mahendrakalkura** [comment]
Can you send me raw data? Your previous messages are not very readable.

**Comment by Peterosh** [comment]
Please forgive my poor expression, I feel I can't say clearly, looool.I uploaded my source code.I'd appreciate it if you could help me find out what the problem is.thank you.

https://github.com/Peterosh/HOOK365.git

**Comment by Peterosh** [comment]
looool,l did it. Thank you for your answer.The message sent has an extra space character

**Comment by isaurav0** [comment]
How do I obtain uid value there?
